version: "3.8"
services:
  mongo:
    image: mongo:5.0
    container_name: typescript-server
    environment:
        - MONGO_INITDB_ROOT_USERNAME=user
        - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    ports:
      - "27020:27017"